import React from "react";

const Definitions = () =>{
 return (<div className="mtop15p mbot15p">
    <div className="blog-desc mtop15p">
                <div className="mbot15p"><h4><b>I. Definitions</b></h4><hr/></div>
                <div>For the purposes of this Privacy Policy:</div>
                <ul>
                    <li className="mtop15p"><b>"Personal Data"</b> refers to any information that relates to an identified or identifiable 
                    individual. This includes, but is not limited to, name, email address, IP address, device ID, and any other data that 
                    could identify a user either directly or indirectly.</li>
                    <li className="mtop15p"><b>"Usage Data"</b> refers to data collected automatically, either generated by the use of the 
                    Site or from the Site infrastructure itself (for example, the duration of a page visit or browser type).</li>
                    <li className="mtop15p"><b>"Cookies"</b> are small files stored on your device (computer, mobile device, etc.) by a 
                    website to remember your actions and preferences over time.</li>
                    <li className="mtop15p"><b>"Data Controller"</b> means the natural or legal person who (either alone or jointly with 
                    others) determines the purposes for which and the manner in which any Personal Data are, or are to be, processed. For 
                    the purposes of this Privacy Policy, we are the Data Controller.</li>
                    <li className="mtop15p"><b>"Data Processor"</b> (or “Service Provider”) means any natural or legal person who processes 
                    the data on behalf of the Data Controller. We may use the services of various third-party Service Providers in order 
                    to process your data more effectively.</li>
                    <li className="mtop15p"><b>"You"</b> refers to the individual accessing or using the Site, or the legal entity on behalf 
                    of which such individual is accessing or using the Site, as applicable.</li>
                    <li className="mtop15p"><b>"Site"</b> refers to our blog, accessible via <b>nellutlalnrao.com</b>, where we share articles, 
                    tutorials, reviews, or other content related to technology.</li>
                    <li className="mtop15p"><b>"Device"</b> means any device that can access the Site, such as a computer, smartphone, or 
                    tablet.</li>
                    <li className="mtop15p"><b>"Third-party Services"</b> refers to external platforms or services that we may use in 
                    conjunction with our blog, such as Google Analytics, advertising networks, social media plugins, or email marketing 
                    tools.</li>
                    <li className="mtop15p"><b>"Consent"</b> means a freely given, specific, informed, and unambiguous indication of the data 
                    subject’s wishes by which they, by a statement or by a clear affirmative action, signify agreement to the processing of 
                    personal data relating to them.</li>
                </ul>
            </div>
 </div>);
};

export default Definitions;