import React from "react";
import { ContainerFluid, Row, Col } from "e-ui-react";
import Header from '@MainTemplates/Header/index.js';
import { HeaderMenu } from '@MainConfig/HeaderMenu.js';
import BlogArticleHeader from '@MainComponents/blog-article-header/index.js';

const PrivacyPolicy = ({ meta }) =>{
 return (<div className="mbot15p">
    <Header menulinks={HeaderMenu} />
    <ContainerFluid>
        <Row>
            <Col md={12}>
                <div>
                    <hr/><h2 className="blog-head" style={{ paddingTop:'15px' }}><b>Privacy Policy</b></h2><hr/>
                </div>
            </Col>
        </Row>
        <Row>
            <Col md={10}>
            <div className="blog-desc mtop15p">
            Welcome to <i><u>nellutlalnrao.com</u></i> (referred to as "we", "our" or "us"). We value your privacy and 
            are committed to protecting the personal information you share with us when accessing or using our 
            website <i><u>nellutlalnrao.com</u></i> (the "Site").<br/><br/>
            This Privacy Policy outlines how we collect, use, store, disclose, and safeguard your information when you visit our 
            blog, interact with our content, or utilize any of our services, including newsletters, comments, and contact forms. 
            Please read this policy carefully to understand our practices regarding your personal data and how we will treat it.<br/><br/>
            By using our Site, you agree to the collection and use of information in accordance with this Privacy Policy. If you 
            do not agree with the practices described herein, please do not access or use the Site.<br/><br/>
            This Privacy Policy is designed to comply with global privacy regulations including, but not limited to:
            <ul>
                <li className="mtop5p"><b>General Data Protection Regulation (GDPR) –</b> applicable to visitors from the European Union (EU)</li>
                <li className="mtop5p"><b>California Consumer Privacy Act (CCPA) –</b> applicable to residents of California, United States</li>
                <li className="mtop5p"><b>Children’s Online Privacy Protection Act (COPPA)</b></li>
                <li className="mtop5p"><b>Other relevant local and international data protection laws</b></li>
            </ul>
            As we continue to grow and expand our offerings, we may update this Privacy Policy from time to time. We encourage you to 
            review it periodically to stay informed about how we are protecting your information.<br/><br/>
            If you have any questions or concerns about this Privacy Policy or our data practices, feel free to contact us 
            at <i><u>me@nellutlalnrao.com</u></i>.
            </div>
            <div className="blog-desc mtop15p">
                <div><h4><b>Definitions</b></h4></div>
                <div>For the purposes of this Privacy Policy:</div>
                <ul>
                    <li className="mtop5p"><b>"Personal Data"</b> refers to any information that relates to an identified or identifiable 
                    individual. This includes, but is not limited to, name, email address, IP address, device ID, and any other data that 
                    could identify a user either directly or indirectly.</li>
                    <li className="mtop5p"><b>"Usage Data"</b> refers to data collected automatically, either generated by the use of the 
                    Site or from the Site infrastructure itself (for example, the duration of a page visit or browser type).</li>
                    <li className="mtop5p"><b>"Cookies"</b> are small files stored on your device (computer, mobile device, etc.) by a 
                    website to remember your actions and preferences over time.</li>
                    <li className="mtop5p"><b>"Data Controller"</b> means the natural or legal person who (either alone or jointly with 
                    others) determines the purposes for which and the manner in which any Personal Data are, or are to be, processed. For 
                    the purposes of this Privacy Policy, we are the Data Controller.</li>
                    <li className="mtop5p"><b>"Data Processor"</b> (or “Service Provider”) means any natural or legal person who processes 
                    the data on behalf of the Data Controller. We may use the services of various third-party Service Providers in order 
                    to process your data more effectively.</li>
                    <li className="mtop5p"><b>"You"</b> refers to the individual accessing or using the Site, or the legal entity on behalf 
                    of which such individual is accessing or using the Site, as applicable.</li>
                    <li className="mtop5p"><b>"Site"</b> refers to our blog, accessible via <b>nellutlalnrao.com</b>, where we share articles, 
                    tutorials, reviews, or other content related to technology.</li>
                    <li className="mtop5p"><b>"Device"</b> means any device that can access the Site, such as a computer, smartphone, or 
                    tablet.</li>
                    <li className="mtop5p"><b>"Third-party Services"</b> refers to external platforms or services that we may use in 
                    conjunction with our blog, such as Google Analytics, advertising networks, social media plugins, or email marketing 
                    tools.</li>
                    <li className="mtop5p"><b>"Consent"</b> means a freely given, specific, informed, and unambiguous indication of the data 
                    subject’s wishes by which they, by a statement or by a clear affirmative action, signify agreement to the processing of 
                    personal data relating to them.</li>
                </ul>
            </div>
            <div className="mtop15p">
                <div><h4><b>Information We Collect</b></h4></div>
                <div className="blog-desc mtop15p">
                    <div>We collect several types of information from and about users of our Site. The information we collect falls into the 
                        following categories:</div>
                    <div>
                        <ol>
                            <li className="mtop5p">
                                <div><b>Personal Information You Voluntarily Provide</b></div>
                                <div className="mtop5p">When you interact with our Site, you may voluntarily provide personal information, including 
                                    but not limited to:</div>
                                <div>
                                    <ul>
                                        <li className="mtop5p">Your <b>name</b> and <b>email address</b> when subscribing to newsletters or leaving comments</li>
                                        <li className="mtop5p">Your <b>contact information</b> when filling out contact forms or participating in surveys</li>
                                        <li className="mtop5p">Any information you include in <b>blog comments</b>, <b>messages</b>, or <b>emails</b> sent to us</li>
                                    </ul>
                                </div>
                            </li>
                            <li className="mtop5p">
                                <div><b>Automatically Collected Information</b></div>
                                <div className="mtop5p">When you visit the Site, we automatically collect certain data using technologies like cookies, log files, and 
                                    analytics tools. This may include:</div>
                                <div>
                                    <ul>
                                        <li className="mtop5p"><b>IP Address</b></li>
                                        <li className="mtop5p"><b>Browser type and version</b></li>
                                        <li className="mtop5p"><b>Device information</b> (e.g., mobile device type, operating system)</li>
                                        <li className="mtop5p"><b>Pages you visited</b>, time spent on those pages, and navigation patterns</li>
                                        <li className="mtop5p"><b>Referring website</b> or URL that brought you to our Site</li>
                                    </ul>
                                </div>
                            </li>
                            <li className="mtop5p">
                                <div><b>Cookies and Similar Technologies</b></div>
                                <div className="mtop5p">We use cookies and similar tracking technologies to enhance your experience on our Site. These may:</div>
                                <div>
                                    <ul>
                                        <li className="mtop5p">Remember your login preferences</li>
                                        <li className="mtop5p">Analyze traffic and user behavior</li>
                                        <li className="mtop5p">Track affiliate links and marketing campaigns</li>
                                    </ul>
                                </div>
                                <div>You can control or disable cookies through your browser settings. More information can be found in 
                                    our <b>Cookies and Tracking Technologies</b> section.</div>
                            </li>
                        </ol>
                    </div>
                </div>
            </div>
            </Col>
        </Row>
    </ContainerFluid>
    
 </div>);
};

export default PrivacyPolicy; 