export const ExamsData = {
    "CAPF": {
        "id": "CAPF",
        "enId": "CAPF",
        "enLabel": "CAPF Assistant Commandants",
        "hiId": "सीएपीएफ",
        "hiLabel": "सीएपीएफ सहायक कमांडर",
        "icon": "fa-shield",
        "enDesc": "Recruitment for Assistant Commandants in Central Armed Police Forces.",
        "hiDesc": "केंद्रीय सशस्त्र पुलिस बलों में असिस्टेंट कमांडेंट की भर्ती।",
        "subjectList":{
            "indian_polity":{
                "id": "indian_polity",
                "enLabel":"Indian Polity",
                "hiLabel":"भारतीय राजव्यवस्था",
                "subjects":{
                    "indian_constitution":{
                        "id": "indian_constitution",
                        "icon": "fa-university",
                        "enLabel": "The Constitution of India",
                        "hiLabel": "भारत का संविधान",
                        "chapters": 14,
                        "topics": 184,
                        "study_hours": 220,
                        "enTags":["CAPF", "CDS", "CGSE", "CMS", "CSE", "ESE", "IES/ISS", "IFoS", "NDA", "RT", "SCRA"],
                        "hiTags":["सीएपीएफ", "सीडीएस", "सीजीएसई", "सीएमएस", "सीएसई", "ईएसई", "आईईएस/आईएसएस", "आई.एफओ.एस", "एनडीए", "आरटी", "एससीआरए"],
                        "is_progress": false
                    }
                }
            }
        }
    },
    "CDS": {
        "id": "CDS",
        "enId": "CDS",
        "enLabel": "Combined Defence Services",
        "hiId": "सीडीएस",
        "hiLabel": "संयुक्त रक्षा सेवाएँ",
        "icon": "fa-fighter-jet",
        "enDesc": "Entry into the Indian Army, Navy and Air Force through CDS.",
        "hiDesc": "सीडीएस के ज़रिए भारतीय थल सेना, नौसेना और वायु सेना में प्रवेश।",
    },
    "CGSE": {
        "id": "CGSE",
        "enId": "CGSE",
        "enLabel": "Combined Geo-Scientist",
        "hiId": "सीजीएसई",
        "hiLabel": "संयुक्त भू-वैज्ञानिक",
        "icon": "fa-globe",
        "enDesc": "Recruitment of Geologists, Geophysicists and related scientific posts.",
        "hiDesc": "भूवैज्ञानिकों, भू-भौतिकविदों और संबंधित वैज्ञानिक पदों की भर्ती।",
    },
    "CMS": {
        "id": "CMS",
        "enId": "CMS",
        "enLabel": "Combined Medical Services",
        "hiId": "सीएमएस",
        "hiLabel": "संयुक्त चिकित्सा सेवाएँ",
        "icon": "fa-user-md",
        "enDesc": "Recruitment of Medical Officers in Central Government services.",
        "hiDesc": "केंद्र सरकार की सेवाओं में मेडिकल अधिकारियों की भर्ती।",
    },
    "CSE": {
        "id": "CSE",
        "enId": "CSE",
        "enLabel": "Civil Services Examination",
        "hiId": "सीएसई",
        "hiLabel": "सिविल सेवा परीक्षा",
        "icon": "fa-university",
        "enDesc": "Recruitment for IAS, IPS, IFS and other Group A & B Civil Services.",
        "hiDesc": "आईएएस, आईपीएस, आईएफएस और अन्य ग्रुप ए और बी सिविल सेवाओं के लिए भर्ती",
    },
    "ESE": {
        "id": "ESE",
        "enId": "ESE",
        "enLabel": "Engineering Services Examination",
        "hiId": "ईएसई",
        "hiLabel": "इंजीनियरिंग सेवा परीक्षा",
        "icon": "fa-cogs",
        "enDesc": "Recruitment of engineers for various Government departments.",
        "hiDesc": "विभिन्न सरकारी विभागों के लिए इंजीनियरों की भर्ती।",
    },
    "IES/ISS": {
        "id": "IES/ISS",
        "enId": "IES/ISS",
        "enLabel": "Indian Economic Service / Indian Statistical Service",
        "hiId": "आईईएस/आईएसएस",
        "hiLabel": "भारतीय आर्थिक सेवा / भारतीय सांख्यिकीय सेवा",
        "icon": "fa-bar-chart",
        "enDesc": "Recruitment for Economics and Statistics professionals.",
        "hiDesc": "अर्थशास्त्र और सांख्यिकी पेशेवरों की भर्ती।",
    },
    "IFoS": {
        "id": "IFoS",
        "enId": "IFoS",
        "enLabel": "Indian Forest Service",
        "hiId": "आई.एफओ.एस",
        "hiLabel": "भारतीय वन सेवा",
        "icon": "fa-tree",
        "enDesc": "Recruitment of officers for the Indian Forest Service.",
        "hiDesc": "भारतीय वन सेवा के लिए अधिकारियों की भर्ती।",
    },
    "NDA": {
        "id": "NDA",
        "enId": "NDA",
        "enLabel": "National Defence Academy & Naval Academy",
        "hiId": "एनडीए",
        "hiLabel": "राष्ट्रीय रक्षा अकादमी और नौसेना अकादमी",
        "icon": "fa-plane",
        "enDesc": "Entry into NDA and Naval Academy for defence officer training.",
        "hiDesc": "डिफेंस ऑफिसर ट्रेनिंग के लिए एनडीए और नेवल एकेडमी में प्रवेश।",
    },
    "RT": {
        "id": "RT",
        "enId": "RT",
        "enLabel": "Recruitment Tests",
        "hiId": "आर टी",
        "hiLabel": "भर्ती परीक्षाएं",
        "icon": "fa-pencil-square-o",
        "enDesc": "Direct recruitment examinations conducted by UPSC.",
        "hiDesc": "यूपीएससी द्वारा आयोजित सीधी भर्ती परीक्षाएं।",
    },
    "SCRA": {
        "id": "SCRA",
        "enId": "SCRA",
        "enLabel": "Special Class Railway Apprentices",
        "hiId": "एससीआरए",
        "hiLabel": "स्पेशल क्लास रेलवे अप्रेंटिस",
        "icon": "fa-train",
        "enDesc": "Special Railway Apprentices recruitment examination.",
        "hiDesc": "विशेष रेलवे अप्रेंटिस भर्ती परीक्षा।",
    }
};